### ISSUE TITLE
[1.16.5] Quark Oddities Backpack Compatibility

### ISSUE THREAD

**Issue by PaperTriangle** [PORTB/BiggerStacks#10]
Would it be possible to add compatibility for the Quark Oddities Backpack?

Currently clicking and dragging items into it will only transfer a maximum of 64 into the inventory slot.

However, shift clicking a stack from your inventory will transfer the full stack.

**EDIT:** I would like to note that this appears to be be due to the method getSlotLimit in the class vazkii.quark.base.handle.ProxiedItemStackHandler

I also noticed the following two classes might also have issues with stack sizes:
vazkii.quark.content.automation.tile.ChuteTileEntity
vazkii.quark.content.management.entity.ChestPassengerEntity

**Comment by PORTB** [comment]
Should be fixed in 1.16/v1.1 and 1.18/v3.1.1
