### ISSUE TITLE
Crash with bundles

### ISSUE THREAD

**Issue by Yupoman** [PORTB/BiggerStacks#12]
When I try to use a bundle the game crashes (even if it's just one item, no a stack)

I know this item isn't officially in yet, but it is in the game without a recipe, I just wanted to make this issue known.
It would be a great a compatibility because the bundle is the solution to the opposite problem of the inventory (small stacks of many items)

It happened to me in my world with other mods in these versions: biggerstacks-1.18-2.9 // forge-1.18.2-40.1.19 (I removed the rest of the mods just in case), and also tried the latest versions: biggerstacks-1.18-4.0 // forge-1.18.2-40.1.52

[crash-2022-06-22_15.57.05-client.txt](https://github.com/PORTB/BiggerStacks/files/8960624/crash-2022-06-22_15.57.05-client.txt)

**Comment by PORTB** [comment]
Should be fixed in v4.1
