### ISSUE TITLE
Incompatibilities i found with 1.18-4.2

### ISSUE THREAD

**Issue by Speecker** [PORTB/BiggerStacks#17]
BiggerStacks seems to be incompatible with mcytjLib Wand mods like ConstructionWand/BuildungWands/NotEnoughWands as they think you woud have 0 items of the material you want to build with even though you do have some in your inventory. The amount does not matter. BuildingGadgets work perfectly fine with it. Maybe you can implement a more or less similar method into BiggerStacks to solve incompatibility with other mods depending on Stackamount counting methods right away (But you may consider the fact that BuildingGadgets method breaks PMMO compatibility, so it would be nice, if possible to not do so).

StorageRacks crashes the entire Game whenever you try to clikc one of the controlllers.

Hope this helps in solving some incompatibilities and make this awesome mod useful.

**Comment by PORTB** [comment]
Thanks for the report 

I tested the construction wand mods and they all worked fine with a stack size of 1000
I also tested storageracks and it worked fine

Are you playing in a modpack or with other mods? Can you post a crash log for the issue with storage racks

**Comment by PORTB** [comment]
Since it has been several months, and I cannot replicate this issue, I am closing it. Though if it is still happening, make another issue on the new issues repo
