### ISSUE TITLE
Whitelist/Blacklist in config?

### ISSUE THREAD

**Issue by AlHollandiyah** [PORTB/BiggerStacks#19]
Feature request: Is it possible to set the whitelist or the blacklist in the config instead of needing craft tweaker to add tags to items? Thank you very much for considering!

Edit: Also Craft Tweaker isn't out for 1.19 yet.

**Comment by PORTB** [comment]
1.18 and 1.16 now have a feature that does this, though I'm assuming you're playing on 1.19 since you mentioned it. It will come to 1.19 soon

**Comment by PORTB** [comment]
This has been added to 1.19
