### ISSUE TITLE
999 stack of potions

### ISSUE THREAD

**Issue by lynrayy** [PORTB/BiggerStacks#22]
Mod incopitable with potions stacker (https://www.curseforge.com/minecraft/mc-mods/stackablepotions-forge). Potions start stacks to 999 instead of 16 or 32

**Comment by PORTB** [comment]
On 1.16 and 1.18 there is now a feature that can replace what that mod does. See https://codeberg.org/PORTB/BiggerStacks/wiki for how to use it. The first example in the examples section at the bottom of the page increases the stack size of potions to 32. 

This mod doesn't add the cooldown though. If you still want to use that other mod, maybe making this mod increase the stacksize of everything *except* potions will work. If you want to do that, put this in your rules file:

```xml
<ruleset version="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://codeberg.org/PORTB/BiggerStacksConfigLib/raw/commit/e768bbe16c39fcd0ec5ee49cb76fe4f585edde1c/extra/schema.xsd">
    <!-- put whatever stacksize you are using here. this will increase the stack size of everything EXCEPT potions -->
    <rule stacksize="32">
        <or>
            <condition>id != minecraft:potion</condition>
            <condition>id != minecraft:lingering_potion</condition>
            <condition>id != minecraft:splash_potion</condition>
        </or>
    </rule>
</ruleset>
```

**Comment by lynrayy** [comment]
Wait. Am i supposed to recompile this mod?

**Comment by PORTB** [comment]
I'm assuming your issue has been fixed? If not, reopen this issue
