### ISSUE TITLE
Does not work with Colossal Chests mod in 1.18.1

### ISSUE THREAD

**Issue by Mitch12354** [PORTB/BiggerStacks#3]
Larger stacks than 64, when placed in the chest are reverted to a stack of 64. Excess items are deleted.

Used Colossal Chests version 1.18.1-1.8.1
and Bigger Stacks version 1.18-2.5

Stack size was set to 4096 if that matters.

**Comment by PORTB** [comment]
should be fixed in v2.6 when cf approves it
