### ISSUE TITLE
[1.18.2] Crash upon loading a world with bonsaitrees3-3.1.0

### ISSUE THREAD

**Issue by PokeMaserJ** [PORTB/BiggerStacks#5]
This is an odd one, both these mods load fine together, that it until you try to create a world. This crash occurs after trying to do so.
https://gist.github.com/PokeMaserJ/b44602ad623387eac861ddb815bf18f3

bonsaitrees3-3.1.0.jar
libnonymous-2.1.0.jar (Library mod)
biggerstacks-1.18-2.7.jar
I don't even know who's side this would be on. But it's these two mods

**Comment by PORTB** [comment]
This and #6 is occurring when I try to copy the settings from the default config to the server config on world creation. I'm not why it's crashing with these mods installed. I will try and find another way of doing that

**Comment by PokeMaserJ** [comment]
Yeah, kind of thought the issue was on your side when I got another crash with a different mod.

**Comment by PORTB** [comment]
The latest changes (v2.9) I have made appear to have fixed this
