### ISSUE TITLE
[1.18.2] Bigger Stack + JAMD Cross mod crash

### ISSUE THREAD

**Issue by PokeMaserJ** [PORTB/BiggerStacks#6]
When creating a world with these mods, you crash. 
biggerstacks-1.18-2.7.jar
JAMD-1.7.0-build.24+mc1.18.2.jar
https://gist.github.com/PokeMaserJ/cbef8b06377943d98137b54add916521

**Comment by PORTB** [comment]
Should be fixed along with #5
